apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
 
namespace: goapp
 
images:
- name: goapp
  newName: tiagodfigueiredo/argocd
  newTag: 00713ec74d32d0cc7520e6c19c4677f5b415de7c
